services:
  - type: web
    name: sankha-realestate-api
    runtime: python
    repo: https://github.com/FrevastramTheCoder/sankha-realestate-backend
    plan: free
    branch: main
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: DATABASE_URL
        value: sqlite:///./sankha-realestate.db
      - key: DEBUG
        value: "False"
      - key: FRONTEND_URL
        value: http://localhost:3000
      - key: JWT_SECRET
        sync: false
      - key: GEOCODING_ENABLED
        value: "true"
      - key: GEOCODER_BASE_URL
        value: https://nominatim.openstreetmap.org
      - key: GEOCODER_USER_AGENT
        value: SankhaRealEstate/1.0
      - key: ROUTING_ENABLED
        value: "true"
      - key: ROUTING_BASE_URL
        value: https://router.project-osrm.org
      - key: ROUTING_SUPPORTED_MODES
        value: driving